language: php

php:
  - '7.1'

branches:
  only:
  - master

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - composer dumpautoload

script:
    - phpunit --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)